---
title: "T1P5.6.7"
author: "Catalina Díaz"
date: "23/8/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Problema 5
```{r}
x=seq (1,10)
y= rep(0.1,10)
plot(x,y,main = "PMF Uniforme Discreta" ,ylab = "f(x)",ylim = c(0,.5))
z=cumsum(y)
plot(x,z,main = "CDF Uniforme Discreta" , ylab = "F(x)",type="s")
```

Problema 6
```{r}
(set.seed(13))
muestra <- sample(1:10,1000000, replace = T, prob= NULL)
mean(muestra)
sd(muestra)^2
w= table(muestra)
hist(muestra, main = "FRECUENCIAS", xlab= "x",)



(set.seed(10))
# Águila =1   Sol=0      (Sólo el número de águilas que se obtiene)
moneda= c(1,0)

# Vector para guardar la cantidad de águilas
sample(moneda, 10, replace = T)
muestra = sample(moneda, 10, replace = T)       
sum(muestra)

#Repetir 10^4

aguila = c()
for(i in 1:10^4){
  
  a= sum(sample(moneda, 10, replace = T))
  
  aguila=c(aguila, a)
  
}

#Primeros 3 lanzamientos
print (aguila[1:3])

#Grafica de frecuencias
hist(aguila, main = "FRECUENCIAS", xlab= "x")

#Grafica de las proporciones
hist(aguila/10, main="PROPORCIONES")

```

Problema 7
```{r}
set.seed(10)

#Valor de bola gris= 1,  bola blanca=0
bolas<-c(rep(1,46),rep(0,49))

#Vector para contar las bolas grises
sample(bolas, 20, replace = F)
muestra = sample(bolas, 20, replace = F)       
sum(muestra)

#Repetir 10^4

BG = c()
for(i in 1:10^4){
  
  b= sum(sample(bolas, 20, replace = T))
  
  BG =c(BG, b)
  
}


#Grafica de frecuencias y comparaciones.

plot(table(BG), xlab = "Cantidad de bolas grises", ylab = "frecuencia", main="Gráfico de frecuencias")

x<-c(0:20)
plot((prop.table(table(BG))),type="h",col="gray", xlab = "", ylab="", main = "Comparación entre simulación y distribución teórica" )
par(new=TRUE)
plot((x+0.1),dhyper(x,46,49,20),type="h", axes= F, col="blue",xlab = "Bolas grises", ylab="Proporción")
legend("topleft", inset=.01, title="",
       c("Simulacion","Hipergeometrica(95,20,46)"), fill=c("blue","red"), horiz=F)
```

